version: "3.8"
services:
  app:
    build: .
    volumes:
      - ./app:/app
      - /app/node_modules
  test:
    extends: "app"
    build:
        context: .
        target: "build"
    command: ["npm", "test"]
